enabled: true

# HTTP代理地址
# 示例格式
# proxy:
# {
#   " http_proxy://": http://127.0.0.1:1081,
#   "https_proxy://": https://127.0.0.1:1081,
# }
proxy: {}

account:
  username: "756176532@qq.com" # Pixiv帐号 (Deprecated)
  password: "xp2015zl" # Pixiv密码 (Deprecated)
  token: "RlfuE7I708YvpFCoKuTYu_kKqGzXVRnfELax0IjdPwY" # Pixiv Refresh Token
  refresh-interval: 1800 # 刷新帐号登录凭证间隔,单位为秒


language: zh-cn # 返回语言, 会影响标签的翻译
